#!/bin/bash
images[0]='720p.jpg'
images[1]='1080p.jpg'
images[2]='4k.jpg'
N_IMG=3
TEST_CASES=3


#echo $FILE_IN >> Time_file.txt

gcc -std=c11 -Wall $1.c -o blur.o -lpthread -lm -fopenmp
for((i=0;i<N_IMG; i+=1))
do 
    TIMES=Time_$1_file_$i.csv
    if [ -f "$TIMES" ]; then 
        rm $TIMES
    fi   

    echo "Kernel_size,Threads,Try_1,Try_2,Try_3" >> $TIMES
    FILE_IN=${images[i]}
    echo $FILE_IN
    for ((k=3;k<=15; k+=2))
    do 
        KERNEL_SZ=$k
        #printf "%i," "$KERNEL_SZ" >> Time_file.txt
        for((c=1;c<=1;c*=2))
        do  
            FILE_OUT=test.jpg
            THREADS=$c
            run_time=0
            printf "%i,%i" "$KERNEL_SZ" "$THREADS" >> $TIMES
            for ((t=0; t<TEST_CASES; t+=1))
            do
                printf ',' >> $TIMES
                ./blur.o $FILE_IN $FILE_OUT $THREADS $KERNEL_SZ >> $TIMES

            done
            
            echo "" >> $TIMES
        done
    done
    echo "Running python script"
   ## python Plots.py <<< "${TIMES} ${images[i]}_$2"
done
