#!/bin/bash
images[0]='720p.jpg'
images[1]='1080p.jpg'
images[2]='4k.jpg'
images[3]='8k.jpg'
N_IMG=4
FILE_KERNEL='emboss.txt'
TEST_CASES=3
blocks[0]=1
blocks[1]=2
blocks[2]=7
blocks[3]=14
blocks[4]=21
blocks[5]=28
sz_block=6
Num_cores_mp=128



#echo $FILE_IN >> Time_file.txt
make clean
make
for((i=0;i<N_IMG; i+=1))
do 
    TIMES=Time_$1_file_$i.csv
    if [ -f "$TIMES" ]; then 
        rm $TIMES
    fi   

    echo "Num_blocks,Threads,Try_1,Try_2,Try_3" >> $TIMES
    FILE_IN=${images[i]}
    echo $FILE_IN
    for ((b=0;b<sz_block; b+=1))
    do 
        BLOCK=${blocks[b]}
        for ((c=2;c<=2*Num_cores_mp;c*=2))
        do  
            THREADS=$c
            FILE_OUT=test.jpg
            run_time=0
            printf "%i,%i" "$BLOCK" "$THREADS" >> $TIMES
            for ((t=0; t<TEST_CASES; t+=1))
            do
                printf ',' >> $TIMES
                echo $FILE_IN $FILE_OUT $BLOCK $THREADS $FILE_KERNEL
                ./blur $FILE_IN $FILE_OUT $BLOCK $THREADS $FILE_KERNEL >> $TIMES

            done
            
            echo "" >> $TIMES
        done
    done
    echo "Running python script"
    #python Plots.py <<< "${TIMES} ${images[i]}_$2"
done
